# Generated by Django 4.2.5 on 2023-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(default='hero', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='long_url',
            field=models.CharField(default='hero', max_length=2000),
            preserve_default=False,
        ),
    ]
